### ISSUE TITLE
Menu does not appear in mobile mode

### ISSUE THREAD

**Issue by tinjure20** [frontity-demos/frontity-examples#11]
After watching the Menu fetch tutorial video, I tried it in my ongoing learning project. I works fine except the menu items does not appear on mobile mode. Any reason? or did I miss something? Thank you

**Comment by mburridge** [comment]
Hi @tinjure20 

No you didn't miss anything. I didn't cover adding it to the mobile menu. The main focus of the tutorial was fetching the menu data from WordPress and getting it into the state.

Tthe `<Nav>` component was then used just as an example of how to use the menu data stored in the state. To get it in the mobile menu you would need to do something similar in the `<MenuModal>` component in [this file](https://github.com/frontity-demos/frontity-examples/blob/master/fetch-menu-from-wp/packages/mars-theme/src/components/menu-modal.js).
